sudo: false
language: go
go:
- "1.12"

cache:
  directories:
  - $GOPATH/pkg/mod
  - $GOPATH/bin
  - $HOME/.cache/go-build

script:
- make test

branches:
  only:
  - master

after_success:
- make -j2 .build/${TRAVIS_REPO_SLUG##*/}.linux.amd64
- cp .build/${TRAVIS_REPO_SLUG##*/}.linux.amd64 .build/${TRAVIS_REPO_SLUG##*/}.x86_64

addons:
  artifacts:
    working_dir: ".build"
    paths:
      - "${TRAVIS_REPO_SLUG##*/}.x86_64"
      - "${TRAVIS_REPO_SLUG##*/}.linux.amd64"
    debug: true
    s3_region: eu-west-1
    s3_bucket: remerge-artifacts
    target_paths: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH
