sudo: false
language: go
go:
- "1.11"

cache:
  directories:
  - $GOPATH/pkg/mod
  - $GOPATH/bin
  - $HOME/.cache/go-build

script:
- make test

branches:
  only:
  - master

after_success:
- make artifacts

addons:
  artifacts:
    working_dir: ".build"
    paths:
    - $(git ls-files -o | grep .tar.gz | tr "\n" ":")
    debug: true
    s3_region: eu-west-1
    s3_bucket: remerge-artifacts
    target_paths: "$TRAVIS_REPO_SLUG"
